name: CI
on:
  push:
  workflow_dispatch:
  schedule:
    # Every Sunday at 12PM UTC
    - cron: "0 12 * * 0"

jobs:
    version-check:
        runs-on: 'ubuntu-latest'
        outputs:
            sby_version: ${{ steps.check.outputs.sby_version }}
        steps:
            - name: check
              id: check
              env:
                BUILD_NUM: ${{ github.run_id }}
              run: |
                sby_latest_rls=$(curl -s -L \
                    -H "Accept: application/vnd.github+json" \
                    -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
                    -H "X-GitHub-Api-Version: 2022-11-28" \
                    https://api.github.com/repos/YosysHQ/sby/git/refs/tags | \
                    jq ".[].ref" | sed -e's%refs/tags/%%' -e 's/\"//g'| sort | tail -n 1)
                echo "sby_latest_rls: ${sby_latest_rls}"
                sby_version=$(echo $sby_latest_rls | sed -e 's/^v//')
                sby_version="0.48"

                echo "sby_version=${sby_version}.${BUILD_NUM}" >> ${GITHUB_OUTPUT}

    build-linux-x86_64:
        runs-on: 'ubuntu-latest'
        needs: version-check
        strategy:
          matrix:
            image: [manylinux_2_34_x86_64]
        steps:
            - uses: actions/checkout@v4
            - name: build
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                BUILD_NUM: ${{ github.run_id }}
                CI_BUILD: 1
                image: ${{ matrix.image }}
                sby_version: ${{ needs.version-check.outputs.sby_version }}
              run: >
                docker run --rm
                --volume "$(pwd):/io"
                --env BUILD_NUM
                --env CI_BUILD
                --env image
                --env sby_version
                --workdir /io
                quay.io/pypa/${{ matrix.image }}
                /io/scripts/build.sh
            - name: upload artifact
              uses: actions/upload-artifact@v4
              with:
                name: "symbiyosys-${{ matrix.image }}"
                path: "release/symbiyosys-${{ matrix.image }}-*.tar.gz"
                if-no-files-found: error
                retention-days: 7

    publish:
        runs-on: 'ubuntu-latest'
        needs:
        - build-linux-x86_64
        - version-check
        permissions:
            contents: write
        steps:
        - name: Download build artifacts
          uses: actions/download-artifact@v4
          with:
            pattern: "symbiyosys-*"
            path: release
            merge-multiple: true
        - name: Create Release
          uses: actions/create-release@v1
          id: create_release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
            tag_name: "v${{ needs.version-check.outputs.sby_version }}"
            release_name: "Release ${{ needs.version-check.outputs.sby_version }}"
            body: |
              Build of Symbiyosys ${{ needs.version-check.outputs.sby_version }}
            draft: false
            prerelease: false
        - name: Upload assets to release
          uses: softprops/action-gh-release@v2
          with:
            tag_name: "v${{ needs.version-check.outputs.sby_version }}"
            files: |
              release/**/*.tar.gz
            fail_on_unmatched_files: true
    # ci-windows:
    #     runs-on: windows-latest
    #     steps:
    #         - uses: msys2/setup-msys2@v2
    #           with:
    #             update: true
    #             install: >-
    #                 gcc
    #                 flex
    #                 bison
    #                 autotools
    #                 help2man
    #                 python3
    #         - uses: actions/checkout@v4
    #         - name: Download source
    #           shell: msys2 {0}
    #           run: |
    #             cwd=$(pwd)
    #             inst=$cwd/verilator-windows-64
    #             ./scripts/build.sh
    #             wget https://github.com/verilator/verilator/archive/refs/tags/v5.030.tar.gz
    #             tar xvf v5.030.tar.gz
    #             cd verilator-5.030
    #             autoconf
    #             ./configure --prefix=$inst
    #             make -j$(nproc)
    #             make install
    #             cd $cwd
    #             cp -r $inst/share/verilator/include $inst
    #             cp $inst/share/verilator/bin/verilator_includer $inst/bin




